services:
  legionlord-postgres:
    image: postgres
    container_name: legionlord-postgres
    volumes:
      - /data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER:
      - POSTGRES_PASSWORD:
    networks:
      - legionlord

  legionlord-backend:
    image: legionlord-backend
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: legionlord-backend
    ports:
      - 9090:9090
    networks:
      - legionlord
    depends_on:
      - legionlord-postgres


  legionlord-frontend:
    image: legionlord-frontend
    build:
      context: .
      dockerfile: docker/frontend/frontend.Dockerfile
    container_name: legionlord-frontend
    ports:
      - 5100:80
    networks:
      - legionlord

  nginx:
    image: legionlord-nginx
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /private/var/services/legionlord/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - legionlord
    depends_on:
      - legionlord-backend

networks:
  legionlord:
    external: true
    name: legionlord_default