services:
  legionlord-postgres:
    image: postgres
    container_name: legionlord-postgres
    volumes:
      - /data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER:
      - POSTGRES_PASSWORD:

  legionlord-backend:
    image: legionlord-backend
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: legionlord-backend
    ports:
      - 10010:10010
    depends_on:
      - legionlord-postgres

  nginx:
    image: legionlord-nginx
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /private/var/services/legionlord/nginx/letsencrypt:/etc/letsencrypt
    depends_on:
      - legionlord-backend