spring:
  datasource:
    url: jdbc:postgresql://5.189.173.249:5432/legionlord
    username: pgadmin
    password: abiFiwan6697+
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/master.changelog.yml
    enabled: true
  jpa:
    show-sql: false
server:
  port: 9090